### ISSUE TITLE
Utility only copies small amount of data

### ISSUE THREAD

**Issue by whelen-cchevalier** [bendrucker/azure-blob-to-s3#14]
My app seems to be only copying some amount of data, then it exits the program. The next time I run it, it copies different data.

```
var MoveData = function () {
    console.log("moving data")
    toS3({
        azure: {
            connection:
                'DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx/xxx==;EndpointSuffix=core.windows.net',
            container: 'xxx'
        },
        concurrency: 100,
        aws: {
            region: 'us-east-1',
            bucket: 'dev-azure-analytics-export',
            accessKeyId: 'xxx',
            secretAccessKey: 'xxxd'
        }
    });
    console.log("data moved")
}

MoveData ();
```

**Comment by whelen-cchevalier** [comment]
I'm observing this with the CLI as well (but only on my EC2 instance, not locally)

**Comment by bendrucker** [comment]
This is not enough information for me to help. Most likely something is going wrong listing data from Azure but I will need you to provide proper logs and perhaps investigate what they reveal before I can devote any time here. Happy to reopen and discuss with sufficient info.

**Comment by whelen-cchevalier** [comment]
Very understandable. My apploigies. Running through the CLI on my EC2 instance I get a series of azure status messages:
```
{"time":"2019-07-23T13:20:46.284Z","hostname":"ip-166-66-6-66","pid":31503,"level":"info",
"name":"azure","message":"page","page":{"token":{"nextMarker":"2!232!M234MTI4IWNvbW1hbmQtY
W5hbHl0aWNzXz2345Y1M2VlNzlkNzQ1N2RhOWEwZmM5M2Nk2341NWVkL0V2ZW50LzIwMTgtMTAtMDcvMjEvYzMzNTZ
kYTEtNzc2ZS00YmY3LWIzYTEtNTU1NGExMzVmNDgzXzIwMTgxMDA3XzIxMzMwNi5ibG9iITAwMDAyOCE5OTk5LTEyL
TMxVDIzOjU5OjU5Ljk5OTk5OTlaIQ--","targetLocation":0},"count":5000}}
```

It will either very immediately or eventually simply stop sending messages and the program will exit. Are there any other log messages you suggest I could look through and what can I do to diagnose the Azure listing conflict?

**Comment by bendrucker** [comment]
I’d be interested in how many items are returned from that list call. Can’t remember off hand if that’s logged. Would recommend cloning and adding logs.

**Comment by whelen-cchevalier** [comment]
Not sure if this is helpful. But when I switched to a beefer EC2 instance, it ran no problems. I was running it in the smallest Linux lightsail option before.

**Comment by bendrucker** [comment]
Possible you were running out of memory though the crashes there come with a pretty explicit log dump before exit. Trying to do 100 concurrent uploads is not going to be reliable from a t class instance. I’d consider it a bug if the program were exiting 0 but beyond that picking appropriate instance types based on your files and desired concurrency is left to the user.
