### ISSUE TITLE
INQUIRY (Not an issue)

### ISSUE THREAD

**Issue by mhmdahmed97** [bendrucker/azure-blob-to-s3#42]
I am relatively new to cloud environments and I have a situation where I need to transfer my data from a blob with 75 containers to AWS buckets. Is there anyway to transfer all 75 container's data to 75 buckets that are created automatically?

or do I have to apply this node.js application 75 times and create 75 s3 buckets manually?

**Comment by bendrucker** [comment]
Yeah this library doesn't quite do that. Feel free to use the API though. You could create the buckets programmatically and then use the API to copy into them.

**Comment by mhmdahmed97** [comment]
Thank you very much Ben, and yes I figured that was the only option, I'll
make the program public when I'm done with it, obviously using your API
along with it. I hope you won't mind
