### ISSUE TITLE
Token error

### ISSUE THREAD

**Issue by kaansen32** [bendrucker/azure-blob-to-s3#7]
I just try to migrate azure blob items to s3 bucket with your codes by using CLI. When ı entered the whole variables, I am getting an error exactly down below. Could you please guide me ?

{"time":"2019-02-21T11:08:52.300Z","hostname":"linuxtest","pid":53288,"level":"info","name":"azure","message":"page","page":{"token":null,"count":1}}
{"time":"2019-02-21T11:08:52.322Z","hostname":"linuxtest","pid":53288,"level":"error","name":"s3","err":{"name":"Error","message":"Missing credentials in config","code":"CredentialsError","stack":"Error: Missing credentials in config\n    at IncomingMessage.<anonymous> (/usr/lib/node_modules/azure-blob-to-s3/node_modules/aws-sdk/lib/util.js:847:34)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:978:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"}}

**Comment by bendrucker** [comment]
How are you providing your AWS credentials?
